# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AVA.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
import iconsfile


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1240, 865)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.drop_shadow_layout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName("drop_shadow_layout")
        self.Main_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Main_Frame.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(84, 79, 129, 255), stop:1 rgba(28, 27, 47, 255));")
        self.Main_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main_Frame.setObjectName("Main_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Main_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Uppe_Frame = QtWidgets.QFrame(self.Main_Frame)
        self.Uppe_Frame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.Uppe_Frame.setStyleSheet("background-color: none\n"
"")
        self.Uppe_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Uppe_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Uppe_Frame.setObjectName("Uppe_Frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Uppe_Frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Upper_Logo = QtWidgets.QFrame(self.Uppe_Frame)
        self.Upper_Logo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Upper_Logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Upper_Logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Upper_Logo.setObjectName("Upper_Logo")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Upper_Logo)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.Upper_Logo)
        self.label.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/AVA Icon2.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.horizontalLayout.addWidget(self.Upper_Logo)
        self.Upper_Btns = QtWidgets.QFrame(self.Uppe_Frame)
        self.Upper_Btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Upper_Btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Upper_Btns.setObjectName("Upper_Btns")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Upper_Btns)
        self.horizontalLayout_4.setContentsMargins(0, 0, 50, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Homebtn_2 = QtWidgets.QPushButton(self.Upper_Btns)
        self.Homebtn_2.setMinimumSize(QtCore.QSize(0, 50))
        self.Homebtn_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Homebtn_2.setFont(font)
        self.Homebtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Homebtn_2.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"}\n"
"QPushButton:hover{\n"
"    color : rgb(35, 193, 219);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 30);\n"
"    border-radius : 25px;\n"
"}")
        self.Homebtn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../icons8-home-96.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Homebtn_2.setIcon(icon)
        self.Homebtn_2.setIconSize(QtCore.QSize(45, 45))
        self.Homebtn_2.setFlat(True)
        self.Homebtn_2.setObjectName("Homebtn_2")
        self.horizontalLayout_4.addWidget(self.Homebtn_2)
        self.AVAbtn = QtWidgets.QPushButton(self.Upper_Btns)
        self.AVAbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.AVAbtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.AVAbtn.setFont(font)
        self.AVAbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AVAbtn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"}\n"
"QPushButton:hover{\n"
"    color : rgb(35, 193, 219);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border-radius : 25px;\n"
"}")
        self.AVAbtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Mic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AVAbtn.setIcon(icon1)
        self.AVAbtn.setIconSize(QtCore.QSize(50, 50))
        self.AVAbtn.setFlat(True)
        self.AVAbtn.setObjectName("AVAbtn")
        self.horizontalLayout_4.addWidget(self.AVAbtn)
        self.CmdListbtn = QtWidgets.QPushButton(self.Upper_Btns)
        self.CmdListbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.CmdListbtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.CmdListbtn.setFont(font)
        self.CmdListbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CmdListbtn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"}\n"
"QPushButton:hover{\n"
"    color : rgb(35, 193, 219);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border-radius : 25px;\n"
"}")
        self.CmdListbtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Commandlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CmdListbtn.setIcon(icon2)
        self.CmdListbtn.setIconSize(QtCore.QSize(60, 60))
        self.CmdListbtn.setFlat(True)
        self.CmdListbtn.setObjectName("CmdListbtn")
        self.horizontalLayout_4.addWidget(self.CmdListbtn)
        self.settingbtn = QtWidgets.QPushButton(self.Upper_Btns)
        self.settingbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.settingbtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.settingbtn.setFont(font)
        self.settingbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingbtn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"}\n"
"QPushButton:hover{\n"
"    color : rgb(35, 193, 219);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border-radius : 25px;\n"
"}")
        self.settingbtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/92a8b221f3f4448b03f08cd607df4f8e.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingbtn.setIcon(icon3)
        self.settingbtn.setIconSize(QtCore.QSize(50, 50))
        self.settingbtn.setFlat(True)
        self.settingbtn.setObjectName("settingbtn")
        self.horizontalLayout_4.addWidget(self.settingbtn)
        self.aboutbtn = QtWidgets.QPushButton(self.Upper_Btns)
        self.aboutbtn.setMinimumSize(QtCore.QSize(0, 50))
        self.aboutbtn.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.aboutbtn.setFont(font)
        self.aboutbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aboutbtn.setStyleSheet("QPushButton{\n"
"    color : white;\n"
"}\n"
"QPushButton:hover{\n"
"    color : rgb(35, 193, 219);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border-radius : 25px;\n"
"}")
        self.aboutbtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutbtn.setIcon(icon4)
        self.aboutbtn.setIconSize(QtCore.QSize(50, 50))
        self.aboutbtn.setFlat(True)
        self.aboutbtn.setObjectName("aboutbtn")
        self.horizontalLayout_4.addWidget(self.aboutbtn)
        self.horizontalLayout.addWidget(self.Upper_Btns)
        self.Upperframe_spacer = QtWidgets.QFrame(self.Uppe_Frame)
        self.Upperframe_spacer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.Upperframe_spacer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Upperframe_spacer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Upperframe_spacer.setObjectName("Upperframe_spacer")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Upperframe_spacer)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(173, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.Upperframe_spacer)
        self.Close_min = QtWidgets.QFrame(self.Uppe_Frame)
        self.Close_min.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Close_min.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Close_min.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Close_min.setObjectName("Close_min")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Close_min)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_btns = QtWidgets.QFrame(self.Close_min)
        self.frame_btns.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Minimize = QtWidgets.QPushButton(self.frame_btns)
        self.Minimize.setMinimumSize(QtCore.QSize(19, 19))
        self.Minimize.setMaximumSize(QtCore.QSize(20, 20))
        self.Minimize.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(35, 193, 219);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(69, 207, 101);\n"
"}")
        self.Minimize.setText("")
        self.Minimize.setObjectName("Minimize")
        self.horizontalLayout_3.addWidget(self.Minimize)
        self.closebtn = QtWidgets.QPushButton(self.frame_btns)
        self.closebtn.setMinimumSize(QtCore.QSize(19, 19))
        self.closebtn.setMaximumSize(QtCore.QSize(20, 20))
        self.closebtn.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(255, 29, 29);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(212, 24, 24);\n"
"}")
        self.closebtn.setText("")
        self.closebtn.setObjectName("closebtn")
        self.horizontalLayout_3.addWidget(self.closebtn)
        self.horizontalLayout_2.addWidget(self.frame_btns)
        self.horizontalLayout.addWidget(self.Close_min)
        self.verticalLayout.addWidget(self.Uppe_Frame)
        self.MidFrame = QtWidgets.QFrame(self.Main_Frame)
        self.MidFrame.setStyleSheet("background-color : none")
        self.MidFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MidFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MidFrame.setObjectName("MidFrame")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.MidFrame)
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.MidFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.gridLayout = QtWidgets.QGridLayout(self.HomePage)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.HomePage)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BottomLabel = QtWidgets.QLabel(self.frame_2)
        self.BottomLabel.setText("")
        self.BottomLabel.setObjectName("BottomLabel")
        self.verticalLayout_2.addWidget(self.BottomLabel)
        self.TopLabel = QtWidgets.QLabel(self.frame_2)
        self.TopLabel.setMaximumSize(QtCore.QSize(670, 280))
        self.TopLabel.setText("")#
        #self.movie = QMovie("icons\\LogoGif.gif")
        #self.TopLabel.setMovie(self.movie)
        #self.movie.start()
        self.TopLabel.setPixmap(QtGui.QPixmap(":/1.png"))
        self.TopLabel.setScaledContents(True)
        self.TopLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TopLabel.setObjectName("TopLabel")
        self.verticalLayout_2.addWidget(self.TopLabel)
        self.MidLabel = QtWidgets.QLabel(self.frame_2)
        self.MidLabel.setText("")
        self.MidLabel.setObjectName("MidLabel")
        self.verticalLayout_2.addWidget(self.MidLabel)
        self.gridLayout.addWidget(self.frame_2, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.HomePage)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.HomePage)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.HomePage)
        self.AVAPage = QtWidgets.QWidget()
        self.AVAPage.setObjectName("AVAPage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.AVAPage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame = QtWidgets.QFrame(self.AVAPage)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.PulsatingGif_Label = QtWidgets.QLabel(self.frame_4)
        self.PulsatingGif_Label.setText("")
        self.PulsatingGif_Label.setObjectName("PulsatingGif_Label")
        self.verticalLayout_5.addWidget(self.PulsatingGif_Label)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.50695, y1:1, x2:0.502299, y2:0.585, stop:0 rgba(0, 0, 0, 66), stop:1 rgba(255, 255, 255, 0));\n"
"color : white;")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_5.addWidget(self.textBrowser)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget_2.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.stackedWidget_2.setFont(font)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.Mic_Page = QtWidgets.QWidget()
        self.Mic_Page.setObjectName("Mic_Page")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.Mic_Page)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.stackedWidget_2.addWidget(self.Mic_Page)
        self.Type_Page = QtWidgets.QWidget()
        self.Type_Page.setObjectName("Type_Page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Type_Page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit = QtWidgets.QLineEdit(self.Type_Page)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color : rgb(0,0,0,0);\n"
"color : white")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_6.addWidget(self.lineEdit)
        self.stackedWidget_2.addWidget(self.Type_Page)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.Bottom_Frame_2 = QtWidgets.QFrame(self.frame)
        self.Bottom_Frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Bottom_Frame_2.setStyleSheet("background-color: none;\n"
"margin-left : 5\n"
"")
        self.Bottom_Frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Bottom_Frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Bottom_Frame_2.setObjectName("Bottom_Frame_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Bottom_Frame_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Bottombtn_container_2 = QtWidgets.QFrame(self.Bottom_Frame_2)
        self.Bottombtn_container_2.setMaximumSize(QtCore.QSize(310, 16777215))
        self.Bottombtn_container_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Bottombtn_container_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Bottombtn_container_2.setObjectName("Bottombtn_container_2")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.Bottombtn_container_2)
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.Speechinputbtn_2 = QtWidgets.QPushButton(self.Bottombtn_container_2)
        self.Speechinputbtn_2.setMinimumSize(QtCore.QSize(69, 69))
        self.Speechinputbtn_2.setMaximumSize(QtCore.QSize(70, 70))
        self.Speechinputbtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Speechinputbtn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(64, 64, 85, 150);\n"
"    border-radius : 30px;\n"
"}")
        self.Speechinputbtn_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/audio-waves.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Speechinputbtn_2.setIcon(icon5)
        self.Speechinputbtn_2.setIconSize(QtCore.QSize(50, 50))
        self.Speechinputbtn_2.setFlat(True)
        self.Speechinputbtn_2.setObjectName("Speechinputbtn_2")
        self.horizontalLayout_13.addWidget(self.Speechinputbtn_2)
        self.line_3 = QtWidgets.QFrame(self.Bottombtn_container_2)
        self.line_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.line_3.setStyleSheet("color: rgb(255, 255, 255,150);\n"
"")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_13.addWidget(self.line_3)
        self.frame_3 = QtWidgets.QFrame(self.Bottombtn_container_2)
        self.frame_3.setMinimumSize(QtCore.QSize(69, 69))
        self.frame_3.setMaximumSize(QtCore.QSize(70, 70))
        self.frame_3.setStyleSheet("background-color : white; \n"
" border-radius : 30")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_13.addWidget(self.frame_3)
        self.line_4 = QtWidgets.QFrame(self.Bottombtn_container_2)
        self.line_4.setStyleSheet("color: rgb(255, 255, 255,150);\n"
"")
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_13.addWidget(self.line_4)
        self.TypeInputbtn_2 = QtWidgets.QPushButton(self.Bottombtn_container_2)
        self.TypeInputbtn_2.setMinimumSize(QtCore.QSize(69, 69))
        self.TypeInputbtn_2.setMaximumSize(QtCore.QSize(70, 70))
        self.TypeInputbtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TypeInputbtn_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(64, 64, 85, 150);\n"
"    border-radius : 30px;\n"
"}")
        self.TypeInputbtn_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/text.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.TypeInputbtn_2.setIcon(icon6)
        self.TypeInputbtn_2.setIconSize(QtCore.QSize(50, 50))
        self.TypeInputbtn_2.setFlat(True)
        self.TypeInputbtn_2.setObjectName("TypeInputbtn_2")
        self.horizontalLayout_13.addWidget(self.TypeInputbtn_2)
        self.horizontalLayout_12.addWidget(self.Bottombtn_container_2)
        self.verticalLayout_3.addWidget(self.Bottom_Frame_2)
        self.horizontalLayout_8.addWidget(self.frame)
        self.stackedWidget.addWidget(self.AVAPage)
        self.CMNDPage = QtWidgets.QWidget()
        self.CMNDPage.setObjectName("CMNDPage")
        self.stackedWidget.addWidget(self.CMNDPage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.stackedWidget.addWidget(self.SettingsPage)
        self.AboutPage = QtWidgets.QWidget()
        self.AboutPage.setObjectName("AboutPage")
        self.stackedWidget.addWidget(self.AboutPage)
        self.horizontalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.MidFrame)
        self.Bottom_Frame = QtWidgets.QFrame(self.Main_Frame)
        self.Bottom_Frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Bottom_Frame.setStyleSheet("background-color: none;\n"
"margin-left : 5\n"
"")
        self.Bottom_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Bottom_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Bottom_Frame.setObjectName("Bottom_Frame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Bottom_Frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout.addWidget(self.Bottom_Frame)
        self.drop_shadow_layout.addWidget(self.Main_Frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setPlaceholderText(_translate("MainWindow", " HELLO WORLD THIS IS JUST A PLACE HOLDER"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Type Here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
